export const defaultCategories = {
  'jayjzcpr': {
    id: 'jayjzcpr',
    name: 'react',
    active: true,
    deleted: false,
  },
  'jayjznks': {
    id: 'jayjznks',
    name: 'redux',
    active: true,
    deleted: false,
  },
  'jayjzz1l': {
    id: 'jayjzz1l',
    name: 'udacity',
    active: true,
    deleted: false,
  },

};

export const defaultPosts = {
  'jayk190l': {
    id: 'jayk190l',
    timestamp: 1503032400000,
    title: 'All the fundamental React.js concepts, jammed into this single Medium article',
    body: 'Last year I wrote a short book on learning React.js which turned out to be about 100 pages. \nThis year, I am going to challenge myself to summarize it as an article on Medium. This article is not going to cover what React is or why you should learn it. Instead, this is a practical introduction to the fundamentals of React.js for those who are already familiar with JavaScript and know the basics of the DOM API.\n\n All code examples below are labeled for reference. They are purely intended to provide examples of concepts. Most of them can be written in a much better way.',
    author: 'Samer Margo',
    category: 'jayjzcpr',
    voteUp: 10,
    voteDown: 0,
    deleted: false,
    commentCount: 1,
  },
  'jaykgp0r': {
    id: 'jaykgp0r',
    timestamp: 1485151200000,
    title: 'Scaling your Redux App with ducks',
    body: 'How does your front-end application scale? How do you make sure that the code you’re writing is maintainable 6 months from now?\nRedux took the world of front-end development by storm in 2015 and established itself as a standard — even beyond the scope of React. At the company where I work, we recently finished refactoring a fairly large React codebase, adding redux instead of reflux. \n\nWe did it because moving forward would have been impossible without a well structured application and a good set of rules. The codebase is more than two years old, and reflux was there from the beginning. We had to change code that wasn’t touched in more than a year and was pretty tangled with the React components. \nBased on the work we did on the project, I put together this repo, explaining our approach in organizing our redux code.',
    author: 'Alex Greg',
    category: 'jayjznks',
    voteUp: 12,
    voteDown: -2,
    deleted: false,
    commentCount: 0,
  },
  'jaykn4do': {
    id: 'jaykn4do',
    timestamp: 1481263200000,
    title: 'Review: Udacity Data Analyst Nanodegree Program',
    body: 'Udacity’s Data Analyst Nanodegree program was one of the first online data science programs in the online education revolution.\n\n\n It aims to “ensure you master the exact skills necessary to build a career in data science.” Does it accomplish its goal? Is it the best option available?',
    author: 'David Melnik',
    category: 'jayjzz1l',
    voteUp: 26,
    voteDown: -12,
    deleted: false,
    commentCount: 2,
  },
};

export const defaultComments = {
  'jaykzyzx': {
    id: 'jaykzyzx',
    parentId: 'jayk190l',
    timestamp: 1512885600000,
    body: 'Hopefully, you’re still reading these posts.',
    author: 'Cartmen',
    voteUp: 12,
    voteDown: 0,
    deleted: false,
    parentDeleted: false,
  },
  'jaykuoij': {
    id: 'jaykuoij',
    parentId: 'jaykn4do',
    timestamp: 1481522400000,
    body: 'Hi there! I am a COMMENT.',
    author: 'Bublik',
    voteUp: 4,
    voteDown: -2,
    deleted: false,
    parentDeleted: false,
  },
  'jaykuygw': {
    id: 'jaykuygw',
    parentId: 'jaykn4do',
    timestamp: 1482386400000,
    body: 'That’s annoying that you can’t get a straight answer. Please do follow up with a response here if you find out!',
    author: 'Anonimus',
    voteUp: 1,
    voteDown: -24,
    deleted: false,
    parentDeleted: false,
  },
};